export const Routes = {
  home: "/",
  contact: "/contact",
  landing: {
    features: "/#how-it-works",
    howItWorks: "/#how-it-works",
    ecosystem: "/#ecosystem",
    calculator: "/#calculator",
    pricing: "/#pricing",
    getStarted: "/auth/sign-up",
  },
  auth: {
    sign_in: "/auth/sign-in",
    sign_up: "/auth/sign-up",
    forgot_password: "/auth/forgot-password",
    reset_password: "/auth/reset-password",
    accept_invite: "/auth/accept-invite",
  },
  onboarding: "/onboarding",
  tip: (storeSlug: string, code: string) =>
    `/${storeSlug}/q/${code}` as const,
  checkoutReturn: "/checkout/return",
  dashboard: {
    root: "/dashboard",
    gettingStarted: "/dashboard/getting-started",
    employees: "/dashboard/employees",
    employeeDetail: (employeeId: string) =>
      `/dashboard/employees/${employeeId}` as const,
    tips: "/dashboard/tips",
    tipDetail: (tipId: string) => `/dashboard/tips/${tipId}` as const,
    reviews: "/dashboard/reviews",
    distribution: "/dashboard/distribution",
    analytics: {
      root: "/dashboard/analytics",
      overview: "/dashboard/analytics/overview",
      tips: "/dashboard/analytics/tips",
      employees: "/dashboard/analytics/employees",
      stores: "/dashboard/analytics/stores",
      insights: "/dashboard/analytics/insights",
    },
    access: "/dashboard/access",
    alerts: "/dashboard/alerts",
    payments: "/dashboard/payments",
    payouts: "/dashboard/payouts",
    account: "/dashboard/account",
    admin: {
      root: "/dashboard/admin",
      users: "/dashboard/admin/users",
      payments: "/dashboard/admin/payments",
      paymentDetail: (id: string) =>
        `/dashboard/admin/payments/${id}` as const,
      payoutDetail: (id: string) => `/dashboard/admin/payouts/${id}` as const,
      analytics: "/dashboard/admin/analytics",
    },
    settings: {
      root: "/dashboard/settings",
      profile: "/dashboard/settings/profile",
      branding: "/dashboard/settings/branding",
      tipping: "/dashboard/settings/tipping",
      localization: "/dashboard/settings/localization",
      reviewRedirect: "/dashboard/settings/review-redirect",
      reviewsFeedback: "/dashboard/settings/reviews-feedback",
      alerts: "/dashboard/settings/alerts",
      members: "/dashboard/settings/members",
      billing: "/dashboard/settings/billing",
      taxDetails: "/dashboard/settings/tax-details",
    },
  },
  employee: {
    root: "/employee",
    reviews: "/employee/reviews",
    qr: "/employee/qr",
  },
  legal: {
    terms: "/legal/terms",
    privacy: "/legal/privacy",
  },
  help: {
    root: "/help",
    category: (categorySlug: string) => `/help/${categorySlug}` as const,
    article: (categorySlug: string, articleSlug: string) =>
      `/help/${categorySlug}/${articleSlug}` as const,
  },
} as const;
