"use client";

import { type FC, type FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowRight, Info, LoaderCircle } from "lucide-react";
import { Routes } from "@/routes/routes";
import { authFieldClassName } from "./auth-password-field";

export const AuthEmployeeForm: FC = () => {
  const [contact, setContact] = useState("");
  const [pin, setPin] = useState("");
  const [isPending, setIsPending] = useState(false);

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setIsPending(true);
    window.setTimeout(() => setIsPending(false), 1000);
  };

  return (
    <div className="auth-fade-enter space-y-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-ink-charcoal">
          Employee Portal
        </h1>
        <p className="mt-1 text-xs text-zinc-500">
          Check your personal tip earnings, payouts, and customer reviews.
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label
            htmlFor="employee-contact"
            className="mb-1.5 block text-xs font-semibold text-zinc-700"
          >
            Your Registered Phone or Email
          </label>
          <input
            id="employee-contact"
            type="text"
            required
            value={contact}
            onChange={(event) => setContact(event.target.value)}
            placeholder="maria@artisancafe.com or (555) 019-2834"
            className={authFieldClassName}
          />
        </div>

        <div>
          <label
            htmlFor="employee-pin"
            className="mb-1.5 block text-xs font-semibold text-zinc-700"
          >
            6-Digit Access PIN or Invite Code
          </label>
          <input
            id="employee-pin"
            type="text"
            required
            maxLength={6}
            value={pin}
            onChange={(event) =>
              setPin(event.target.value.replace(/\D/g, "").slice(0, 6))
            }
            placeholder="• • • • • •"
            className={`${authFieldClassName} text-center font-mono text-sm font-bold tracking-widest`}
          />
        </div>

        <div className="flex items-start gap-2 rounded-xl border border-brand-200/60 bg-brand-50/60 p-3 text-xs text-brand-900">
          <Info
            className="mt-0.5 size-4 shrink-0 text-electric-lime"
            strokeWidth={2}
          />
          <span>
            Your invite PIN was generated by your manager on the delitip.com
            dashboard.
          </span>
        </div>

        <button
          type="submit"
          disabled={isPending}
          className="flex w-full items-center justify-center gap-2 rounded-xl bg-ink-charcoal py-3 text-xs font-semibold text-paper-offwhite shadow transition hover:bg-zinc-800 disabled:opacity-70"
        >
          {isPending ? (
            <>
              <LoaderCircle className="size-4 animate-spin" strokeWidth={2} />
              <span>Authenticating...</span>
            </>
          ) : (
            <>
              <span>Access My Tip Profile</span>
              <ArrowRight className="size-3.5" strokeWidth={2} />
            </>
          )}
        </button>
      </form>

      <div className="pt-2 text-center">
        <p className="text-xs text-zinc-500">
          Are you an employer?{" "}
          <Link
            href={Routes.auth.sign_in}
            className="font-bold text-brand-700 hover:underline"
          >
            Business sign in
          </Link>
        </p>
      </div>
    </div>
  );
};
